version: '3'

services:
  app:
    build:
      context: . # docker build .
    ports: # --publish 8000:8000
      - 8000:8000
    volumes:
      - agenda-db:/app
      - ./agenda:/app/agenda
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000" # CMD
    env_file:
      - ./.env
  redis:
    image: redis:alpine
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - 8025:8025
  celery:
    build:
      context: .
    command: celery -A core worker -Q celery --loglevel=INFO
    env_file:
      - ./.env
    depends_on:
      - app
      - redis
volumes:
  agenda-db:
